sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master


matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.5 WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.5


before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=6.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |

script:
  - phpenv config-rm xdebug.ini
  - phpunit
